version: "2.1"
services:
  movies-service:
    container_name: movies-service
    build: ./services/movies/
    volumes:
      - './services/movies:/usr/src/app'
      - './services/movies/package.json:/usr/src/package.json'
    environment:
      - NODE_ENV=${NODE_ENV}
    ports:
      - '3001:3000' # expose ports - HOST:CONTAINER

  web-service:
    container_name: web-service
    build: ./services/web/
    volumes:
      - './services/web:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3007:3006' # expose ports - HOST:CONTAINER
    environment:
      - NODE_ENV=${NODE_ENV}
    depends_on:
      movies-service:
        condition: service_started
    links:
      - movies-service
