version: "2.1"
services:
  movies-service:
    command: yarn dev -- -L
    build: .
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_URI_TESTS=mongodb://mongodb:27017
      - MONGO_URI=mongodb://mongodb:27017
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
